# Generated by Django 5.2.16 on 2026-07-31 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.85)),
                ('rec_type', models.CharField(choices=[('FREQUENTLY_BOUGHT', 'Frequently Bought Together'), ('SIMILAR', 'Similar Product'), ('PERSONALIZED', 'Personalized Pick')], default='FREQUENTLY_BOUGHT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_from', to='products.product')),
                ('recommended_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_to', to='products.product')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
